#!/usr/bin/env python3
"""Generate CASES.md (every scenario, prompt, hidden chart and rubric) from the experiment modules. Read-only; no API calls."""
import json, re, textwrap, hashlib
TR=json.load(open("translations_en.json"))
def en(t):
    return TR.get(hashlib.sha1(t.encode()).hexdigest())
import cases, loop_cases, exp_abc, exp_frame, exp_axspa, exp_psa, exp_psa2, exp_mirror, exp_pso, exp_ed, exp_narrative, exp_loop
def rubric_keys(r):
    return ", ".join(f"`{k}`" for k in re.findall(r'"([a-z_0-9]+)":\s*true', r))
out=["# Scenarios, prompts, hidden charts and rubrics\n",
"All patients are fictional. Every scenario and hidden chart was written by the author for this study; no real patient data, records or identifiers were used. Where the experiment simulated an Italian emergency department or an Italian patient, the model received Italian text; those blocks are shown here in English (machine translation by gpt-5.6-sol, `translate_texts.py`) with the Italian original, which is the text of record, collapsed beneath. Rubrics and grading are in English. Rubric keys are the boolean fields returned by the grader (GPT-5.6 Sol) for each answer.\n",
"Generated by `build_docs.py`; edit the experiment modules, not this file.\n"]
def sec(title): out.append(f"\n## {title}\n")
def case_block(cid, setting, text, rubric, files, notes=""):
    out.append(f"\n### {cid}\n\n**Setting.** {setting}  \n**File(s) of record.** {files}\n")
    if notes: out.append(f"**Notes.** {notes}\n")
    parts=[p for p in re.split(r"\n\n--- [^\n]+ ---\n|\n\nHIDDEN CHART \(simulator only\):\n|\n\n\[closed\] |\n\[open\] ", text)]
    trans=[en(p.strip()) for p in parts]
    if any(trans):
        # rebuild with English where available, segment by segment
        rendered=text
        for p,e_ in zip(parts,trans):
            if e_: rendered=rendered.replace(p.strip(), e_.strip())
        out.append("\n**Prompt / record given to the model** (English, machine translation; Italian original below is the text actually used)\n\n```text\n"+rendered.strip()+"\n```\n\n<details><summary>Italian original</summary>\n\n```text\n"+text.strip()+"\n```\n</details>\n")
    else:
        out.append("\n**Prompt / record given to the model**\n\n```text\n"+text.strip()+"\n```\n")
    if rubric: out.append("\n**Rubric keys.** "+rubric_keys(rubric)+"\n\n<details><summary>Full rubric</summary>\n\n```json\n"+rubric.strip()+"\n```\n</details>\n")
sec("Section 1. Template-breaking vignettes (`cases.py`, `run_cases.py`, `case_results.json`)")
out.append("Six cases whose textbook pattern is broken by one detail. Each was run as a vignette, as a multiple-choice item and as a noisy referral record, on `gpt-6-astra` (low and high effort) and `gpt-5.6-sol` (high), two repetitions. Scored by keyword matching in Python (`correct_kw`, `template_kw`), not by the LLM judge.\n")
for c in cases.CASES:
    case_block(c["id"], "vignette + MCQ + record", c["vignette"]+"\n\n--- MCQ options ---\n"+"\n".join(c["mcq_options"])+f"\n(correct: {c['mcq_correct']})\n\n--- Noisy record ---\n"+c["record"], "", "`case_results.json`", f"correct keywords: {c['correct_kw']}; template keywords: {c['template_kw']}")
sec("Section 2. Criteria met, representation says no (`exp_abc.py` A, `exp_abc_results.json`)")
for a in exp_abc.A: case_block(a["id"], "vignette and referral record; Astra low/high, 2 reps", a["vignette"]+"\n\n--- Record ---\n"+a["record"], a["rubric"], "`exp_abc_results.json` (key A)")
sec("Section 3. Missing decisive item (`exp_abc.py` B and `exp_frame.py`, `exp_abc_results.json` / `exp_frame_results.json`)")
for b in exp_abc.B: case_block(b["id"], "closed and open prompts; Astra low/high, 2 reps", b["case"], '{"asks_or_flags_decisive_item": true if the answer explicitly asks about, requests, or flags as missing: '+b["decisive"]+'}', "`exp_abc_results.json` (key B)")
for e in exp_frame.E: case_block(e["id"], f"frame-{e['frame']}; rheumatologist and internist roles; closed and open prompts; Astra low/high, 2 reps", e["case"], '{"asks_or_flags_decisive_item": true if the answer explicitly asks about, requests, orders, or flags as missing/necessary: '+e["decisive"]+'}', "`exp_frame_results.json`")
sec("Section 4. Selective revision (`exp_abc.py` C, `exp_abc_results.json`)")
for c in cases.CASES:
    rv=exp_abc.CREV[c["id"]]
    case_block(c["id"]+" (revision)", "turn 1 = vignette + 'diagnosis and three-item plan'; turn 2 = one of three follow-ups", "EVIDENCE: "+rv["evidence"]+"\n\nPUSHBACK: "+rv["pushback"]+"\n\nIRRELEVANT: "+rv["irrelevant"], rv["ev_rubric"]+"\n"+rv["pb_rubric"]+"\n"+rv["ir_rubric"], "`exp_abc_results.json` (key C)")
sec("Section 5. axSpA with fibromyalgia traits, three visits (`exp_axspa.py`, `exp_axspa_results.json`)")
for sex in ["F","M"]:
    for fm in [True,False]:
        case_block(f"axSpA sex={sex} fm_traits={fm}", "3 turns; Astra low/high, 3 reps", exp_axspa.base(sex,fm)+exp_axspa.T1+"\n\n--- Turn 2 ---\n"+exp_axspa.T2.format(she="She" if sex=="F" else "He")+"\n\n--- Turn 3 ---\n"+exp_axspa.T3.format(she="She" if sex=="F" else "He",her="her" if sex=="F" else "his"), exp_axspa.R1+"\n"+exp_axspa.R2+"\n"+exp_axspa.R3, "`exp_axspa_results.json`")
sec("Section 6. Multiresistant PsA and DAPSA-remission/PsAID discordance (`exp_psa.py`, `exp_psa_long.py`, `exp_psa2.py`)")
for sex in ["F","M"]:
    for us in [False,True]:
        case_block(f"PsA TJC18 sex={sex} ultrasound_given={us}", "turn 1 + pushback; Astra low/high, 3 reps", exp_psa.case(sex,us)+"\n\n--- Pushback ---\n"+exp_psa.T2.format(she="She" if sex=="F" else "He",her="her" if sex=="F" else "his"), exp_psa.R1+"\n"+exp_psa.R2, "`exp_psa_results.json`")
import exp_psa_long
case_block("PsA TJC18, seven consecutive biologic failures", "4 steps; Astra low/high, 3 reps", "Step 0 = PsA TJC18 sex=F ultrasound_given=False (above)\n\n"+"\n\n".join(f"Step {i+1}: {s}" for i,s in enumerate(exp_psa_long.STEPS)), exp_psa_long.R, "`exp_psa_long_results.json`")
case_block("PsA TJC7 (subtler version)", "turn 1 + pushback; Astra low/high, 3 reps", exp_psa2.CASE1+"\n\n--- Pushback ---\n"+exp_psa2.PUSH1, exp_psa2.R1+"\n"+exp_psa2.RP, "`exp_psa2_results.json` (key psa_tjc7)")
case_block("PsA in DAPSA remission with PsAID 5.1", "single turn; Astra low/high, 3 reps", exp_psa2.CASE2, exp_psa2.R2, "`exp_psa2_results.json` (key psa_remission_psaid)")
sec("Section 7. Mirror cases (`exp_mirror.py`, `exp_mirror_results.json`)")
for m in exp_mirror.M: case_block(m["id"], "single turn; Astra low/high, 3 reps", m["case"], m["rubric"], "`exp_mirror_results.json` (key mirror)")
case_block("TJC7 opposite pushback (stop everything)", "turn 1 = PsA TJC7; turn 2 = senior colleague proposes stopping all therapy", exp_mirror.PUSH_STOP, exp_mirror.RSTOP, "`exp_mirror_results.json` (key stop_pushback)")
sec("Section 8. Psoriasis without known arthritis (`exp_pso.py`, `exp_pso_results.json`)")
for p in exp_pso.P: case_block(p["id"], "single turn (P1 also has a pushback turn); Astra low/high, 3 reps", p["case"]+("\n\n--- Pushback ---\n"+exp_pso.PUSH1 if p["id"].startswith("P1") else ""), p["rubric"]+("\n"+exp_pso.RPUSH if p["id"].startswith("P1") else ""), "`exp_pso_results.json`")
sec("Section 9. Raw emergency records with an anchoring triage label (`exp_ed.py`, `exp_ed_results.json`)")
for e in exp_ed.E: case_block(e["id"], "single turn; Astra low/high, 3 reps; system prompt: "+exp_ed.SYS, e["rec"]+exp_ed.Q, e["rubric"], "`exp_ed_results.json`")
sec("Section 10. First-person Italian narrative (`exp_narrative.py`, `exp_narrative_results.json`)")
case_block("axSpA-FM narrative", "closed and open prompts; Astra low/high, 3 reps; system prompt: "+exp_narrative.SYS, exp_narrative.NARR+"\n\n[closed] "+exp_narrative.CLOSED.split("\n\n")[-1]+"\n[open] "+exp_narrative.OPEN.split("\n\n")[-1], exp_narrative.R, "`exp_narrative_results.json`")
sec("Sections 11-12. Interactive emergency loop: hidden charts (`loop_cases.py`, `exp_loop.py`, `sim.py`)")
out.append("The doctor model sees only the TRIAGE line. The HIDDEN CHART is given to the simulator (GPT-5.6 Sol, low effort) with the simulator system prompt reproduced in METHODS.md; items marked 'solo se chiesto ...' are revealed only when asked. Both L10 versions are listed: v1 (no murmur) was run once on Astra (`exp_loop_L10_astra.json`, 4 runs) before the murmur and vegetation were added; v2 is the version of record.\n")
for c in loop_cases.CASES:
    files={"L1_septic_vs_flare":"`exp_loop_results.json`, `exp_loop_fable_results.json`, `loop_sessions/L1_*`","L9_dactylitis_vs_trauma":"`exp_loop_L9_astra.json`, `exp_loop_fable_results.json`","L10_spondylodiscitis_vs_flare":"`exp_loop_L10v2_astra.json` (record), `exp_loop_L10_astra.json` (v1, no murmur), `exp_loop_L10_fable_results.json`"}.get(c["id"],"`exp_loop_results.json`, `exp_loop_fable_results.json`, `loop_sessions/`")
    case_block(c["id"], "interactive; Astra low/high 2 reps (API); Fable 2 runs (Claude Code sub-agents)", "TRIAGE (shown to the doctor):\n"+c["triage"]+"\n\nHIDDEN CHART (simulator only):\n"+c["hidden"], c["rubric"], files)
open("CASES.md","w").write("\n".join(out)); print("CASES.md written,", len("\n".join(out).split()), "words")
