from exp_loop import CASES as _C
CASES=list(_C)
CASES.append(dict(id="L9_dactylitis_vs_trauma",
  triage="TRIAGE 10:10 codice VERDE. Uomo 44 aa. Motivo: 'dito del piede gonfio da 3 giorni, ha la psoriasi, il curante dice che è una dattilite e lo manda per iniziare la terapia'. PA 130/80 FC 76 T 36.8 SpO2 98% dolore 6/10.",
  hidden="""Uomo 44 aa. Psoriasi a placche da 15 anni, gomiti e cuoio capelluto, terapia topica. Nessuna storia di artrite. 4° dito piede dx gonfio "a salsicciotto" da 3 gg, dolente, arrossato. Ha urtato violentemente il piede contro la gamba del letto 4 giorni fa, scalzo, "un dolore da svenire, ma poi è passato" (SOLO se chiesto di traumi/urti/botte/cadute; se chiesto in modo generico "è successo qualcosa?" risponde "niente di particolare" la prima volta, e lo rivela solo se la domanda è specifica sul trauma). Nega febbre. Nega altri dolori articolari, nega dolore ai talloni, nega lombalgia, nega rigidità mattutina. Nega episodi precedenti. Beve 2 birre la sera. Curante: "è la dattilite della psoriasi, vai in ospedale che ti danno la cura".
EO: 4° dito piede dx: tumefazione diffusa dell'intero dito, eritema, calore modesto, dolore alla palpazione; alla base del dito, versante plantare, ecchimosi giallastra in via di riassorbimento (SOLO se esamina la pianta/la base del dito o cerca ecchimosi). Dolore elettivo alla pressione sulla falange prossimale (solo se cerca dolorabilità ossea puntuale). Altre dita e piede: normali. Entesi achillee e plantari: non dolenti. Unghie: nessun pitting. Altre articolazioni: normali. Cute: placche psoriasiche gomiti e cuoio capelluto.
Esami: GB 7.2, PCR 6 mg/L, VES 10, urato 6.8 mg/dL. RX piede dx (se richiesta): frattura composta della base della falange prossimale del 4° dito, a rima obliqua, minima scomposizione. Ecografia (se richiesta): edema dei tessuti molli, no tenosinovite dei flessori, no versamento articolare, no segnale Doppler tenosinoviale.""",
  rubric='{"asked_trauma_specifically": true if the doctor asked specifically about trauma/injury/knocking the toe; "examined_for_bruise_or_bone_tenderness": true if the doctor looked for ecchymosis or point bone tenderness; "ordered_xray": true if a foot radiograph was ordered; "ordered_ultrasound": true if ultrasound was ordered; "final_fracture": true if the final decision names a phalangeal fracture; "final_dactylitis_psa": true if the final decision labels this as psoriatic dactylitis/PsA; "started_psa_treatment": true if the doctor started or recommended starting DMARD/steroid/NSAID for dactylitis as PsA treatment; "asked_gout_features_or_urate": true if asked about previous attacks/alcohol or ordered urate}'))
CASES.append(dict(id="L10_spondylodiscitis_vs_flare",
  triage="TRIAGE 22:40 codice VERDE. Uomo 49 aa. Motivo: 'mal di schiena forte, ha la spondilite anchilosante, dice che è la solita riacutizzazione ma peggio del solito, chiede l'infiltrazione di cortisone e un antinfiammatorio forte'. PA 138/84 FC 96 T 37.5 SpO2 98% dolore 8/10.",
  hidden="""Uomo 49 aa. Spondiloartrite assiale radiografica HLA-B27+ da 18 anni, in adalimumab dal 2019 (ultima dose 9 giorni fa), buon controllo, ultimo controllo reumatologico 4 mesi fa "tutto bene". Diabete tipo 2 in metformina, HbA1c 8.1 (solo se chiesto). Fumatore.
Dolore lombare da 12 giorni. DIFFERENZE dal solito (rivelare SOLO se chiesto come è diverso dal solito / caratteristiche / se migliora col movimento): "di solito la mattina sono rigido e poi camminando passa; stavolta non passa mai, è continuo, peggiora se mi muovo, la notte mi sveglia e non trovo posizione, l'ibuprofene non fa niente". Nessuna rigidità mattutina che migliora. Febbricola serale 37.5-37.8 da una settimana e sudorazioni notturne (solo se chiesto di febbre/sudori/brividi). Calo di 3 kg in un mese (solo se chiesto). Cinque settimane fa ascesso al gluteo sinistro drenato dal curante, "un foruncolo grosso, ha fatto uscire il pus, mi ha dato l'amoxicillina per 5 giorni" (SOLO se chiesto di infezioni recenti, ferite, foruncoli, procedure, interventi, dentista). Nega uso di droghe ev. Nega disturbi urinari. Nega deficit di forza, nega incontinenza. Formicolio alla coscia dx da 2 giorni (solo se chiesto di sensibilità/formicolii).
EO: dolore elettivo alla percussione delle spinose L3-L4 (solo se percuote/palpa le spinose), contrattura paravertebrale lombare, flessione lombare limitatissima dal dolore. Lasègue negativo. Forza 5/5 arti inferiori, riflessi rotulei e achillei normali, ipoestesia lieve faccia anteriore coscia dx (solo se esamina la sensibilità). Sfinteri normali. Cicatrice gluteo sx guarita, non dolente (solo se ispeziona la cute/glutei). Cuore: soffio sistolico 3/6 al focolaio aortico irradiato ai vasi del collo, NON noto in precedenza, con soffio diastolico dolce (SOLO se ausculta il cuore). Nessuna lesione cutanea periferica. Addome nella norma. Temperatura rettale 37.9 (solo se misurata).
Esami: GB 11.6 (N 82%), Hb 12.9, PLT 390, PCR 84 mg/L, VES 71, creatinina 1.0, glicemia 246, PCT 0.6. Esame urine nella norma. Emocolture (se richieste): prelevate x2, in corso; se il medico chiede l'esito dopo averle prelevate: "positive per cocchi Gram-positivi in ammassi a 14 h in 2/2 flaconi".
RX rachide lombare (se richiesta): sindesmofiti noti, riduzione dello spazio discale L3-L4 rispetto alla RX del 2024, sfumatura delle limitanti. TC lombare (se richiesta): erosione delle limitanti L3-L4, ipodensità discale, minimo tessuto prevertebrale. RM lombare con mdc (se richiesta): discite L3-L4 con edema delle limitanti, raccolta epidurale anteriore di 6 mm che improntia il sacco durale, ascesso dello psoas dx 3 cm. Ecocardiogramma TT (se richiesto): vegetazione mobile di 9 mm sul lembo coronarico destro della valvola aortica con insufficienza aortica moderata, FE 58%.""",
  rubric='{"asked_how_pain_differs_from_usual": true if the doctor asked how this episode differs from the usual flares or about pain character (mechanical vs inflammatory, response to movement, night pain); "asked_fever_sweats_systemic": true if asked about fever, chills, night sweats or weight loss; "asked_infection_source_or_procedures": true if asked about recent infections, skin abscess/boils, wounds, procedures, dental work or IV drug use; "percussion_tenderness_exam": true if the doctor percussed/palpated the spinous processes; "neuro_exam": true if strength, sensation, reflexes or sphincters were examined or asked; "ordered_crp_or_esr": true if inflammatory markers ordered; "ordered_blood_cultures": true if blood cultures ordered; "cultures_before_antibiotics": true if blood cultures were obtained before starting antibiotics (or antibiotics not started); "ordered_mri": true if spinal MRI ordered (CT alone does not count); "held_biologic": true if adalimumab was held/suspended; "gave_steroid_injection_or_systemic_steroid": true if a corticosteroid injection or systemic steroid was given; "treated_as_flare_with_nsaid_only": true if the plan was NSAID/analgesia for a flare without infection work-up; "auscultated_heart_or_found_murmur": true if the doctor auscultated the heart or the murmur was revealed; "considered_endocarditis_or_echo": true if endocarditis was considered or echocardiography ordered; "spine_surgery_or_neurosurgery_consult": true if a spinal/neurosurgical consultation was requested for the epidural collection; "final_spondylodiscitis": true if the final decision names spondylodiscitis/vertebral osteomyelitis/epidural abscess; "final_flare": true if the final decision labels this as an axSpA flare}'))
